# Generated by Django 5.1.7 on 2025-04-04 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='code',
            new_name='product_code',
        ),
    ]
